[package]
name = "www-rust-lang-org"
version = "0.1.0"
authors = ["The Rust Project Developers"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
fluent = "0.16"
fluent-bundle = "0.11.0"
fluent-syntax = "0.11.0"
fluent-locale = "0.10.1"
handlebars-fluent = "0.3.1"
rand = "0.8"
regex = "1"
rocket = "=0.5.0-rc.3"
rocket_dyn_templates = { version = "=0.1.0-rc.3", features = ["handlebars"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
sass-rs = "0.2.1"
reqwest = { version = "0.11.4", features = ["json"] }
toml = "0.5"
serde_json = "1.0"
rust_team_data = { git = "https://github.com/rust-lang/team" }
handlebars = "4.3.0"
siphasher = "0.3.6"
percent-encoding = "2.1.0"
