name: CI
on: [push, pull_request]
env:
  RUST_BACKTRACE: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Formatting
        run: |
          # Install extra rustup components
          rustup component add rustfmt
          cargo fmt --all -- --check

      - name: Test
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          # Check if the code is good
          cargo build --all --locked
          cargo test --all --locked

      - name: Build the Docker image
        run: docker build -t website .
